import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import { ToastContainer } from "react-toastify";
import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
import { GlobalContextProvider } from "@/context/store";

// Import DM Sans font with desired weights and subsets
const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
  weight: ["400", "500", "700"], // Include the font weights you need
});

export const metadata: Metadata = {
  title: "Insta Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth antialiased">
      <body className={`${dmSans.variable}`}>
        <GlobalContextProvider>{children}</GlobalContextProvider>
        <ToastContainer />
      </body>
    </html>
  );
}
